import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeProvider";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create gamedb App",
  description: "Generated by create gamedb app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <main className="bg-white dark:bg-gray-900 min-h-screen text-gray-900 dark:text-white">
            <Navbar/>
          {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
